/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BacRouteImport } from './routes/bac'
import { Route as Bac2k27RouteImport } from './routes/bac-2k27'
import { Route as ClothesRouteImport } from './routes/clothes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BacRoute = BacRouteImport.update({
  id: '/bac',
  path: '/bac',
  getParentRoute: () => rootRouteImport,
} as any)
const Bac2k27Route = Bac2k27RouteImport.update({
  id: '/bac-2k27',
  path: '/bac-2k27',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothesRoute = ClothesRouteImport.update({
  id: '/clothes',
  path: '/clothes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bac': typeof BacRoute
  '/bac-2k27': typeof Bac2k27Route
  '/clothes': typeof ClothesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bac': typeof BacRoute
  '/bac-2k27': typeof Bac2k27Route
  '/clothes': typeof ClothesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bac': typeof BacRoute
  '/bac-2k27': typeof Bac2k27Route
  '/clothes': typeof ClothesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/bac' | '/bac-2k27' | '/clothes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/bac' | '/bac-2k27' | '/clothes'
  id: '__root__' | '/' | '/admin' | '/bac' | '/bac-2k27' | '/clothes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BacRoute: typeof BacRoute
  Bac2k27Route: typeof Bac2k27Route
  ClothesRoute: typeof ClothesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac': {
      id: '/bac'
      path: '/bac'
      fullPath: '/bac'
      preLoaderRoute: typeof BacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac-2k27': {
      id: '/bac-2k27'
      path: '/bac-2k27'
      fullPath: '/bac-2k27'
      preLoaderRoute: typeof Bac2k27RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothes': {
      id: '/clothes'
      path: '/clothes'
      fullPath: '/clothes'
      preLoaderRoute: typeof ClothesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BacRoute: BacRoute,
  Bac2k27Route: Bac2k27Route,
  ClothesRoute: ClothesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
