import { useEffect, useState } from 'react'
import { Link, Route, Routes, useNavigate } from 'react-router-dom'
import './App.css'
import { ProtectedRoute } from './components/ProtectedRoute'
import { useCart } from './context/CartContext'
import { bacProducts, getStormProduct, stormProducts, type StormProduct } from './data/catalog'
import { AdminPage } from './pages/AdminPage'
import { AuthPage } from './pages/AuthPage'
import { ContentPage } from './pages/ContentPage'
import { ProductDetailPage } from './pages/ProductDetailPage'

type IconName = 'arrow' | 'arrowUp' | 'bag' | 'bolt' | 'close' | 'menu' | 'minus' | 'plus'
function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, React.ReactNode> = { arrow: <path d="M4 12h15m-6-6 6 6-6 6" />, arrowUp: <path d="m5 19 14-14M8 5h11v11" />, bag: <><path d="M5.5 8.5h13l-1 11h-11l-1-11Z" /><path d="M9 8.5V7a3 3 0 0 1 6 0v1.5" /></>, bolt: <path d="m13.5 2-8 12h6l-1 8 8-12h-6l1-8Z" />, close: <path d="m6 6 12 12M18 6 6 18" />, menu: <path d="M4 7h16M4 12h16M4 17h16" />, minus: <path d="M5 12h14" />, plus: <path d="M12 5v14M5 12h14" /> }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}
const asset = (name: string) => `https://raw.githubusercontent.com/ouhibiaziz22-stack/azix-electric-pulse/main/src/assets/${name}`

function Countdown() {
  const calc = () => { const diff = Math.max(0, new Date('2027-06-01T00:00:00Z').getTime() - Date.now()); return [Math.floor(diff / 86400000), Math.floor(diff / 3600000) % 24, Math.floor(diff / 60000) % 60, Math.floor(diff / 1000) % 60] }
  const [time, setTime] = useState(calc)
  useEffect(() => { const id = window.setInterval(() => setTime(calc()), 1000); return () => window.clearInterval(id) }, [])
  return <div className="pulse-countdown">{time.map((value, index) => <div key={index}><b>{String(value).padStart(2, '0')}</b><span>{['DAYS', 'HOURS', 'MINS', 'SECS'][index]}</span></div>)}</div>
}
function PulseBrand() { return <Link className="pulse-brand" to="/">AZIX<span>.</span></Link> }

function PulseProductCard({ product, onAdd }: { product: StormProduct; onAdd: (product: StormProduct, size: string) => void }) {
  const [size, setSize] = useState('')
  const [warning, setWarning] = useState(false)
  return <article className="pulse-product-card"><Link to={`/products/${product.id}`} className="pulse-product-image"><img src={product.image} alt={product.name} loading="lazy" /><span>{product.badge || 'AZIX / CORE'}</span><i><Icon name="bolt" size={14} /> AZIX STANDARD</i></Link><div className="pulse-product-info"><div><h3>{product.name}</h3><p>{product.subtitle}</p></div><b>{product.price} DT</b></div><div className="pulse-product-actions"><div>{['S', 'M', 'L', 'XL'].map((option) => <button key={option} onClick={() => { setSize(option); setWarning(false) }} className={size === option ? 'picked' : ''}>{option}</button>)}</div><button onClick={() => { if (!size) { setWarning(true); return }; onAdd(product, size) }}><Icon name="plus" size={16} /> {product.preorder ? 'PRE-ORDER' : 'ADD TO BAG'}</button></div>{warning && <small className="pulse-warning">SELECT A SIZE FIRST.</small>}</article>
}

function Ticker() { return <div className="pulse-ticker" aria-hidden="true"><div>{Array.from({ length: 5 }, (_, index) => <span key={index}>AZIX <Icon name="bolt" size={15} /> BUILT DIFFERENT <Icon name="bolt" size={15} /> WEAR THE VOLTAGE <Icon name="bolt" size={15} /></span>)}</div></div> }

function Bag({ onClose, onRequest }: { onClose: () => void; onRequest: () => void }) {
  const { items, count, total, updateQuantity, removeItem } = useCart()
  return <div className="pulse-layer"><button className="pulse-backdrop" onClick={onClose} aria-label="Close bag" /><aside className="pulse-bag"><header><div><span>AZIX / YOUR SELECTION</span><h2>YOUR BAG <sup>{count}</sup></h2></div><button onClick={onClose}><Icon name="close" /></button></header><div className="pulse-bag-lines">{items.length ? items.map((item) => { const product = getStormProduct(String(item.product.id)); return <article key={item.id}><img src={product.image} alt="" /><div><button className="pulse-remove" onClick={() => removeItem(item.id)}>REMOVE</button><h3>{item.product.name}</h3><span>SIZE {item.size}</span><b>{item.total * item.quantity} DT</b><div className="pulse-qty"><button onClick={() => updateQuantity(item.id, -1)}><Icon name="minus" size={13} /></button><i>{item.quantity}</i><button onClick={() => updateQuantity(item.id, 1)}><Icon name="plus" size={13} /></button></div></div></article> }) : <div className="pulse-empty"><Icon name="bag" size={39} /><h3>NOTHING IN HERE YET.</h3><p>Good things start with a choice.</p></div>}</div>{items.length > 0 && <footer><div><span>ESTIMATED TOTAL</span><b>{total} DT</b></div><p>Pre-orders are requests, not payments. We’ll follow up with availability and next steps.</p><button onClick={onRequest}>REQUEST PRE-ORDER <Icon name="arrowUp" /></button></footer>}</aside></div>
}

function RequestModal({ kind, onClose }: { kind: 'preorder' | 'bulk'; onClose: () => void }) {
  const [sent, setSent] = useState(false)
  return <div className="pulse-modal-layer"><button className="pulse-backdrop" onClick={onClose} aria-label="Close request form" /><section className="pulse-modal">{sent ? <div className="pulse-success"><span>REQUEST RECEIVED</span><h2>YOU'RE ON<br /><em>THE LIST.</em></h2><p>Thanks — AZIX will follow up with details and next steps.</p><button onClick={onClose}>BACK TO AZIX <Icon name="arrow" /></button></div> : <><button className="pulse-close" onClick={onClose}><Icon name="close" /></button><span>AZIX / {kind === 'bulk' ? 'CLASS ORDERS' : 'YOUR REQUEST'}</span><h2>{kind === 'bulk' ? <>OUTFIT THE<br /><em>WHOLE CLASS.</em></> : <>MAKE IT<br /><em>YOURS.</em></>}</h2><p>{kind === 'bulk' ? 'Tell us about your class order and we’ll get back to you with the details.' : 'Send your selection and we’ll follow up to confirm availability and how to order.'}</p><form onSubmit={(event) => { event.preventDefault(); setSent(true) }}><div><label>YOUR NAME<input required placeholder="Full name" /></label><label>EMAIL ADDRESS<input required type="email" placeholder="you@example.com" /></label></div>{kind === 'bulk' && <div><label>SCHOOL / GROUP<input required placeholder="Your school or group" /></label><label>ESTIMATED QUANTITY<input required type="number" min="1" defaultValue="20" /></label></div>}<label>ANYTHING ELSE? <small>OPTIONAL</small><textarea rows={3} placeholder="Tell us more about what you need" /></label><button type="submit">{kind === 'bulk' ? 'SEND BULK INQUIRY' : 'SEND PRE-ORDER REQUEST'} <Icon name="arrowUp" /></button><i>No payment is taken now. We’ll contact you by email.</i></form></>}</section></div>
}

function PulseHeader({ view, onBag }: { view: 'home' | 'clothes' | 'bac'; onBag: () => void }) {
  const [open, setOpen] = useState(false)
  return <><div className="pulse-announcement"><Icon name="bolt" size={13} /> INDEPENDENT UNIFORM FOR THE NEXT GENERATION <Icon name="bolt" size={13} /></div><header className="pulse-header"><PulseBrand /><nav className={open ? 'open' : ''}><Link className={view === 'clothes' ? 'active' : ''} to="/clothes" onClick={() => setOpen(false)}>CLOTHES</Link><Link className={view === 'bac' ? 'active' : ''} to="/bac-2k27" onClick={() => setOpen(false)}>BAC 2K27 <Icon name="bolt" size={12} /></Link></nav><div><span>EST. FOR WHAT'S NEXT</span><button onClick={onBag} aria-label="Open bag"><Icon name="bag" /><b>+</b></button><button className="pulse-menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Icon name={open ? 'close' : 'menu'} /></button></div></header></>
}

function PulseStorefront({ view }: { view: 'home' | 'clothes' | 'bac' }) {
  const [bagOpen, setBagOpen] = useState(false)
  const [request, setRequest] = useState<'preorder' | 'bulk' | null>(null)
  const { addItem } = useCart()
  const navigate = useNavigate()
  const catalog = view === 'bac' ? bacProducts : stormProducts.slice(0, 3)
  const add = (product: StormProduct, size: string) => { addItem({ product: { id: product.id, name: product.name, price: product.price }, category: product.id.startsWith('bac-') ? 'bac' : 'main', total: product.price, size, color: product.colors[0].value, colorName: product.colors[0].name }); setBagOpen(true) }
  return <div className="pulse-shell"><PulseHeader view={view} onBag={() => setBagOpen(true)} />
    {view === 'home' && <main><section className="pulse-hero"><img src={asset('azix-hero.jpg')} alt="AZIX black streetwear campaign" /><div className="pulse-lightning"><svg viewBox="0 0 400 700" preserveAspectRatio="none"><path d="M216 -20 177 111 202 151 144 258 169 287 103 423 133 431 38 713" /><path d="M145 259 250 231 290 151" /></svg></div><div><span><i /> NEW ERA / NO RULES</span><h1>WEAR THE<br /><em>VOLTAGE.</em></h1><p>Built different. Worn louder. Everyday essentials for the ones who refuse to blend in.</p><section><Link to="/clothes">SHOP CLOTHES <Icon name="arrowUp" /></Link><Link to="/bac-2k27">EXPLORE BAC 2K27 <Icon name="arrow" /></Link></section></div><footer><span>AZIX / DROP 001</span><span>SCROLL TO EXPLORE ↓</span></footer></section><Ticker /><section className="pulse-collection"><PulseHeading kicker="01 / THE EVERYDAY UNIFORM" title={<>THE CORE<br /><em>COLLECTION.</em></>} text="Uncompromising shapes. Everyday armor. Designed to move how you move." action="VIEW ALL CLOTHES" to="/clothes" /><div className="pulse-grid">{catalog.map((product) => <PulseProductCard product={product} onAdd={add} key={product.id} />)}</div></section><section className="pulse-bac-teaser"><img src={asset('bac-campaign.jpg')} alt="Class of 2027 campaign" loading="lazy" /><div><span>02 / LIMITED CAPSULE</span><PulseBadge /><h2>THE FUTURE<br />LOOKS <em>LOUD.</em></h2><p>One class. One moment. A collection made to mark the year you’ll never forget.</p><Countdown /><Link to="/bac-2k27">ENTER THE 2K27 DROP <Icon name="arrowUp" /></Link></div></section></main>}
    {view === 'clothes' && <main><section className="pulse-intro"><span>AZIX / DROP 001</span><h1>THE CORE<br /><em>COLLECTION.</em></h1><p>Oversized silhouettes. Heavyweight feel. Nothing extra, everything intentional.</p><b>001 — 003</b></section><Ticker /><section className="pulse-collection"><PulseHeading kicker="ESSENTIALS / NO COMPROMISE" title={<>BUILT TO<br /><em>STAND OUT.</em></>} text="Find your fit. Select your size. Make it yours." /><div className="pulse-grid">{catalog.map((product) => <PulseProductCard product={product} onAdd={add} key={product.id} />)}</div></section></main>}
    {view === 'bac' && <main><section className="pulse-bac-hero"><div><img src={asset('bac-campaign.jpg')} alt="Class of 2027 under lightning" /><span>CLASS OF 2027 / THE CAPSULE</span></div><article><span>LIMITED CAPSULE / CLASS OF 2027</span><PulseBadge /><h1>THIS IS<br /><em>YOUR YEAR.</em></h1><p>For the late nights, the last bell, and everything that comes next. Your class. Your moment. Your uniform.</p><small>COUNTING DOWN TO THE CLASS OF 2027</small><Countdown /><section><button onClick={() => document.querySelector('#capsule')?.scrollIntoView({ behavior: 'smooth' })}>SHOP THE CAPSULE ↓</button><button onClick={() => setRequest('bulk')}>BULK INQUIRY <Icon name="arrowUp" /></button></section></article></section><Ticker /><section className="pulse-collection" id="capsule"><PulseHeading kicker="02 / YOUR YEAR, YOUR GEAR" title={<>THE 2K27<br /><em>CAPSULE.</em></>} text="Made for the memories you haven’t made yet. Pre-order your piece of the year." /><div className="pulse-grid pulse-capsule-grid">{catalog.map((product) => <PulseProductCard product={product} onAdd={add} key={product.id} />)}<article className="pulse-bulk"><Icon name="bolt" size={32} /><span>FOR THE WHOLE CLASS</span><h3>BETTER<br />TOGETHER.</h3><p>Outfit your whole class in AZIX. Tell us what you need and we’ll take it from there.</p><button onClick={() => setRequest('bulk')}>ASK ABOUT BULK ORDERS <Icon name="arrowUp" /></button></article></div></section></main>}
    <footer className="pulse-footer"><div><PulseBrand /><p>NOT MADE TO FIT IN.<br />MADE TO STAND OUT.</p><section><Link to="/clothes">CLOTHES <Icon name="arrowUp" /></Link><Link to="/bac-2k27">BAC 2K27 <Icon name="arrowUp" /></Link></section></div><small>© 2026 AZIX. ALL RIGHTS RESERVED. <span>POWERED BY THE NEXT GENERATION <Icon name="bolt" size={12} /></span></small></footer>{bagOpen && <Bag onClose={() => setBagOpen(false)} onRequest={() => { setBagOpen(false); setRequest('preorder') }} />}{request && <RequestModal kind={request} onClose={() => setRequest(null)} />}</div>
}
function PulseBadge() { return <div className="pulse-badge"><Icon name="bolt" size={20} /><span>BAC <b>2K27</b></span><Icon name="bolt" size={20} /></div> }
function PulseHeading({ kicker, title, text, action, to }: { kicker: string; title: React.ReactNode; text: string; action?: string; to?: string }) { return <header className="pulse-heading"><div><span>{kicker}</span><h2>{title}</h2></div><aside><p>{text}</p>{action && to && <Link to={to}>{action} <Icon name="arrowUp" /></Link>}</aside></header> }

function App() { return <Routes><Route path="/" element={<PulseStorefront view="home" />} /><Route path="/clothes" element={<PulseStorefront view="clothes" />} /><Route path="/bac-2k27" element={<PulseStorefront view="bac" />} /><Route path="/products/:id" element={<ProductDetailPage />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route path="/admin/*" element={<ProtectedRoute adminOnly><AdminPage /></ProtectedRoute>} /><Route path="/:page" element={<ContentPage />} /></Routes> }
export default App
